export const ErrorMessages: Record<string, string> = {
    // Auth
    LOGIN_USERNAME_EMPTY: "El nombre de usuario es requerido",
    LOGIN_PASSWORD_EMPTY: "La contraseña es requerida",

    // Brand
    BRAND_NAME_EMPTY: "El nombre de la marca es requerido",
    BRAND_NAME_INVALID: "El nombre de la marca es inválido",
    BRAND_NAME_MIN_LENGTH: "El nombre de la marca es demasiado corto",
    BRAND_DESCRIPTION_MAX_LENGTH: "La descripción es demasiado larga",
    BRAND_LOGO_FILE_INVALID: "El archivo del logo es inválido",
    BRAND_LOGO_FILE_SIZE_EXCEEDED: "El tamaño del logo es muy grande",
    BRAND_UPDATE_EMPTY: "Debe proporcionar al menos un campo para actualizar",

    // Cash Movement
    CASH_MOVEMENT_CASH_SESSION_ID_EMPTY: "La sesión de caja es requerida",
    CASH_MOVEMENT_CASH_SESSION_ID_NEGATIVE: "ID de sesión inválido",
    CASH_MOVEMENT_AMOUNT_EMPTY: "El monto es requerido",
    CASH_MOVEMENT_AMOUNT_NEGATIVE: "El monto no puede ser negativo",
    CASH_MOVEMENT_CONCEPT_EMPTY: "El concepto es requerido",
    CASH_MOVEMENT_CONCEPT_MAX_LENGTH: "El concepto es demasiado largo",
    CASH_MOVEMENT_MOVEMENT_TYPE_INVALID: "Tipo de movimiento inválido",

    // Cash Session
    CASH_SESSION_OPENING_BALANCE_NULL: "El balance de apertura es requerido",
    CASH_SESSION_OPENING_BALANCE_NEGATIVE: "El balance de apertura no puede ser negativo",
    CASH_SESSION_CLOSING_BALANCE_NULL: "El balance de cierre es requerido",
    CASH_SESSION_CLOSING_BALANCE_NEGATIVE: "El balance de cierre no puede ser negativo",
    CASH_SESSION_NOTES_MAX_LENGTH: "Las notas son demasiado largas",

    // Category
    CATEGORY_NAME_EMPTY: "El nombre de la categoría es requerido",
    CATEGORY_NAME_MIN_LENGTH: "El nombre es demasiado corto",
    CATEGORY_NAME_MAX_LENGTH: "El nombre es demasiado largo",
    CATEGORY_DESCRIPTION_MAX_LENGTH: "La descripción es demasiado larga",
    CATEGORY_NAME_DESCRIPTION_SAME: "El nombre y descripción no pueden ser iguales",

    // Customer
    CUSTOMER_FIRSTNAME_INVALID: "El nombre es inválido",
    CUSTOMER_FIRST_NAME_EMPTY: "El nombre es requerido",
    CUSTOMER_FIRST_NAME_MIN_LENGTH: "El nombre es demasiado corto",
    CUSTOMER_LASTNAME_INVALID: "El apellido es inválido",
    CUSTOMER_LAST_NAME_EMPTY: "El apellido es requerido",
    CUSTOMER_LAST_NAME_MIN_LENGTH: "El apellido es demasiado corto",
    CUSTOMER_EMAIL_EMPTY: "El correo electrónico es requerido",
    CUSTOMER_EMAIL_INVALID: "El correo electrónico es inválido",
    CUSTOMER_EMAIL_MAX_LENGTH: "El correo es demasiado largo",
    CUSTOMER_PHONE_NUMBER_EMPTY: "El teléfono es requerido",
    CUSTOMER_PHONE_NUMBER_MIN_LENGTH: "El teléfono es demasiado corto",
    CUSTOMER_ADDRESS_EMPTY: "La dirección es requerida",
    CUSTOMER_ADDRESS_TOO_LONG: "La dirección es demasiado larga",
    CUSTOMER_ADDRESS_MAX_LENGTH: "La dirección excede el límite",
    CUSTOMER_RFC_INVALID: "El RFC es inválido",
    CUSTOMER_ZIPCODE_LENGTH: "El código postal debe tener 5 dígitos",
    CUSTOMER_ZIPCODE_INVALID: "El código postal es inválido",
    CUSTOMER_INVALID_GENERIC_USAGE: "Uso genérico inválido",
    CUSTOMER_UPDATE_EMPTY: "Debe proporcionar al menos un campo para actualizar",

    // Customer Account
    CUSTOMER_ACCOUNT_CUSTOMER_ID_INVALID: "ID de cliente inválido",
    CUSTOMER_ACCOUNT_CREDIT_LIMIT_INVALID: "Límite de crédito inválido",
    CUSTOMER_ACCOUNT_IS_CREDIT_ENABLED_INVALID: "Valor de crédito habilitado inválido",
    CUSTOMER_ACCOUNT_ID_INVALID: "ID de cuenta inválido",
    CUSTOMER_ACCOUNT_MOVEMENT_TYPE_INVALID: "Tipo de movimiento inválido",
    CUSTOMER_ACCOUNT_AMOUNT_INVALID: "Monto inválido",
    CONCEPT_TOO_LONG: "El concepto es demasiado largo",

    // User
    USER_NAME_REQUIRED: "El nombre es requerido",
    USER_NAME_TOO_SHORT: "El nombre es demasiado corto",
    USER_USERNAME_REQUIRED: "El nombre de usuario es requerido",
    USER_USERNAME_TOO_SHORT: "El nombre de usuario es demasiado corto",
    USER_EMAIL_INVALID: "El correo electrónico es inválido",
    USER_PASSWORD_REQUIRED: "La contraseña es requerida",
    USER_PASSWORD_TOO_SHORT: "La contraseña es demasiado corta (mínimo 8 caracteres)",
    USER_PASSWORD_INVALID_FORMAT: "La contraseña debe contener mayúsculas, minúsculas y números",
    USER_ROLE_ID_INVALID: "El rol seleccionado es inválido",
    USER_UPDATE_NO_FIELDS: "Debe proporcionar al menos un campo para actualizar",

    // Movement
    MOVEMENT_PRODUCT_VARIANT_ID_REQUIRED: "El producto es requerido",
    MOVEMENT_USER_ID_REQUIRED: "El empleado es requerido",
    MOVEMENT_QUANTITY_CHANGED_REQUIRED: "La cantidad es requerida",
    MOVEMENT_CUSTOMER_ID_REQUIRED: "El cliente es requerido",
    MOVEMENT_TYPE_REQUIRED: "El tipo de movimiento es requerido",
    MOVEMENT_REFERENCE_DOC_REQUIRED: "El documento de referencia es requerido",
    MOVEMENT_REFERENCE_DOC_MAX_LENGTH: "El documento de referencia es demasiado largo",
    MOVEMENT_REASON_REQUIRED: "La razón es requerida",
    MOVEMENT_REASON_MIN_LENGTH: "La razón es demasiado corta",
    MOVEMENT_REASON_MAX_LENGTH: "La razón es demasiado larga",

    // Payment
    PAYMENT_METHOD_REQUIRED: "El método de pago es requerido",
    PAYMENT_METHOD_INVALID: "El método de pago es inválido",
    PAYMENT_AMOUNT_INVALID: "El monto del pago es inválido",

    // Product Master
    PRODUCT_MASTER_NAME_REQUIRED: "El nombre del producto es requerido",
    PRODUCT_MASTER_NAME_MIN_LENGTH: "El nombre es demasiado corto",
    PRODUCT_MASTER_DESCRIPTION_REQUIRED: "La descripción es requerida",
    PRODUCT_MASTER_DESCRIPTION_MIN_LENGTH: "La descripción es demasiado corta",
    PRODUCT_MASTER_BRAND_ID_REQUIRED: "La marca es requerida",
    PRODUCT_MASTER_CATEGORY_ID_REQUIRED: "La categoría es requerida",
    PRODUCT_MASTER_UPDATE_REQUIRED: "Debe proporcionar al menos un campo para actualizar",

    // Product Variant
    VARIANT_PRODUCT_MASTER_ID_REQUIRED: "El producto maestro es requerido",
    VARIANT_BARCODE_REQUIRED: "El código de barras es requerido",
    VARIANT_PRICE_REQUIRED: "El precio es requerido",
    VARIANT_MIN_STOCK_REQUIRED: "El stock mínimo es requerido",
    VARIANT_DISCOUNT_INVALID: "El descuento es inválido",
    VARIANT_DISCOUNT_EXCEEDS_PRICE: "El descuento no puede ser mayor al precio",
    VARIANT_IMAGE_FILE_TYPE_NOT_ALLOWED: "Tipo de archivo no permitido",
    VARIANT_IMAGE_FILE_SIZE_EXCEEDED: "El tamaño de la imagen es muy grande",
    VARIANT_ID_REQUIRED: "El ID de variante es requerido",
    VARIANT_QUANTITY_INVALID: "La cantidad es inválida",
    VARIANT_UNIT_PRICE_INVALID: "El precio unitario es inválido",

    // Provider
    PROVIDER_COMPANY_NAME_REQUIRED: "El nombre de la compañía es requerido",
    PROVIDER_COMPANY_NAME_TOO_SHORT: "El nombre es demasiado corto (mínimo 3 caracteres)",
    PROVIDER_COMPANY_NAME_TOO_LONG: "El nombre es demasiado largo (máximo 100 caracteres)",
    PROVIDER_TAX_ID_REQUIRED: "El RFC es requerido",
    PROVIDER_TAX_ID_TOO_SHORT: "El RFC debe tener al menos 12 caracteres",
    PROVIDER_TAX_ID_TOO_LONG: "El RFC no puede exceder 13 caracteres",
    PROVIDER_ADDRESS_REQUIRED: "La dirección es requerida",
    PROVIDER_ADDRESS_TOO_LONG: "La dirección es demasiado larga (máximo 200 caracteres)",
    PROVIDER_CONTACT_NAME_REQUIRED: "El nombre de contacto es requerido",
    PROVIDER_CONTACT_NAME_TOO_SHORT: "El nombre de contacto es demasiado corto",
    PROVIDER_CONTACT_EMAIL_REQUIRED: "El correo de contacto es requerido",
    PROVIDER_CONTACT_EMAIL_INVALID: "El correo de contacto es inválido",
    PROVIDER_CONTACT_PHONE_REQUIRED: "El teléfono de contacto es requerido",
    PROVIDER_CONTACT_PHONE_TOO_SHORT: "El teléfono debe tener al menos 10 dígitos",
    PROVIDER_CONTACT_PHONE_INVALID: "El teléfono debe tener exactamente 10 dígitos",
    PROVIDER_UPDATE_NO_FIELDS: "Debe proporcionar al menos un campo para actualizar",

    // Purchase Order
    PURCHASE_ORDER_ORDER_NUMBER_REQUIRED: "El número de orden es requerido",
    PURCHASE_ORDER_ORDER_NUMBER_MAX_LENGTH: "El número de orden es demasiado largo",
    PURCHASE_ORDER_PROVIDER_ID_REQUIRED: "El proveedor es requerido",
    PURCHASE_ORDER_CREATED_BY_REQUIRED: "El creador es requerido",
    PURCHASE_ORDER_TOTAL_AMOUNT_REQUIRED: "El monto total es requerido",
    PURCHASE_ORDER_EXPECTED_DELIVERY_DATE_REQUIRED: "La fecha de entrega es requerida",
    PURCHASE_ORDER_EXPECTED_DELIVERY_DATE_FUTURE: "La fecha de entrega debe ser futura",
    PURCHASE_ORDER_RECEIVED_DATE_FUTURE: "La fecha de recepción no puede ser futura",
    PURCHASE_ORDER_DETAILS_REQUIRED: "Los detalles de la orden son requeridos",
    PURCHASE_ORDER_DETAILS_MAX_COUNT: "Máximo de detalles excedido",
    PURCHASE_ORDER_VARIANT_ID_REQUIRED: "El producto es requerido",
    PURCHASE_ORDER_QUANTITY_ORDERED_REQUIRED: "La cantidad es requerida",
    PURCHASE_ORDER_UNIT_PRICE_REQUIRED: "El precio unitario es requerido",
    PURCHASE_ORDER_STATUS_INVALID: "El estado es inválido",
    PURCHASE_ORDER_COMMENTS_MAX_LENGTH: "Los comentarios son demasiado largos",
    PURCHASE_ORDER_UPDATE_EMPTY: "Debe proporcionar al menos un campo para actualizar",

    // Role
    ROLE_NAME_REQUIRED: "El nombre del rol es requerido",
    ROLE_NAME_MIN_LENGTH: "El nombre es demasiado corto",
    ROLE_NAME_MAX_LENGTH: "El nombre es demasiado largo",
    ROLE_DESCRIPTION_MAX_LENGTH: "La descripción es demasiado larga",
    ROLE_NAME_DESCRIPTION_SAME: "El nombre y descripción no pueden ser iguales",
    ROLE_UPDATE_EMPTY: "Debe proporcionar al menos un campo para actualizar",

    // Sale
    SALE_CUSTOMER_ID_INVALID: "ID de cliente inválido",
    SALE_CREATED_BY_INVALID: "ID de creador inválido",
    SALE_DETAILS_REQUIRED: "Los detalles de la venta son requeridos",
    SALE_DETAILS_MAX_COUNT_EXCEEDED: "Máximo de productos excedido",
    SALE_DETAILS_DUPLICATE_PRODUCTS: "Hay productos duplicados en la venta",
    SALE_ID_INVALID: "ID de venta inválido",
    SALE_STATUS_INVALID: "Estado de venta inválido",

    // Auth Domain
    AUTH_INVALID_CREDENTIALS: "Nombre de usuario o contraseña incorrectos. Por favor, inténtalo de nuevo.",
    AUTH_USER_INACTIVE: "El usuario está inactivo",
    AUTH_INVALID_REFRESH_TOKEN: "El token de refresco es inválido o expirado",
    AUTH_USER_NOT_AUTHENTICATED: "Usuario no autenticado",

    // Domain Errors - Common
    CONFLICT: "El recurso ya existe o conflicta con el estado actual",
    DOMAIN_ERROR: "Error de dominio",

    // Domain - NotFound
    BRAND_NOT_FOUND: "Marca no encontrada",
    CASH_SESSION_NOT_FOUND: "Sesión de caja no encontrada",
    CASH_MOVEMENT_NOT_FOUND: "Movimiento de efectivo no encontrado",
    CATEGORY_NOT_FOUND: "Categoría no encontrada",
    CUSTOMER_NOT_FOUND: "Cliente no encontrado",
    CUSTOMER_ACCOUNT_NOT_FOUND: "Cuenta de cliente no encontrada",
    CUSTOMER_ACCOUNT_MOVEMENT_NOT_FOUND: "Movimiento de cuenta no encontrado",
    USER_NOT_FOUND: "Empleado no encontrado",
    MOVEMENT_NOT_FOUND: "Movimiento no encontrado",
    PRODUCTMASTER_NOT_FOUND: "Producto no encontrado",
    PRODUCTVARIANT_NOT_FOUND: "Variante de producto no encontrada",
    PRODUCTVARIANT_NOT_FOUND_BY_BARCODE: "Producto no encontrado por código de barras",
    PROVIDER_NOT_FOUND: "Proveedor no encontrado",
    PURCHASE_ORDER_NOT_FOUND: "Orden de compra no encontrada",
    ROLE_NOT_FOUND: "Rol no encontrado",
    SALE_NOT_FOUND: "Venta no encontrada",
    SESSION_NOT_FOUND: "Sesión de caja no encontrada o en estado inválido",

    // Domain - Exists/Duplicate
    BRAND_NAME_EXISTS: "El nombre de la marca ya existe",
    CATEGORY_NAME_EXISTS: "El nombre de la categoría ya existe",
    CUSTOMER_ACCOUNT_ALREADY_EXISTS: "La cuenta de cliente ya existe",
    USER_USERNAME_EXISTS: "El nombre de usuario ya existe",
    PRODUCTMASTER_NAME_EXISTS: "El nombre del producto ya existe",
    PRODUCTVARIANT_BARCODECODE_ALREADY_EXISTS: "El código de barras ya existe",
    PRODUCTVARIANT_SKU_ALREADY_EXISTS: "El SKU ya existe",
    PROVIDER_NAME_EXISTS: "El nombre del proveedor ya existe",
    ROLE_NAME_EXISTS: "El nombre del rol ya existe",

    // Domain - Business Logic
    CASH_SESSION_ALREADY_OPEN: "Ya existe una sesión de caja abierta",
    MOVEMENT_INSUFFICIENT_STOCK: "Stock insuficiente",
    MOVEMENT_INVALID_QUANTITY: "Cantidad inválida",
    MOVEMENT_UNAUTHORIZED_CREATION: "No autorizado para crear el movimiento",
    PURCHASE_ORDER_CREATION_FAILED: "Falló la creación de la orden de compra",
    ROLE_PROTECTED: "El rol está protegido y no puede modificarse",
    SALE_CREATION_FAILED: "Falló la creación de la venta",
    SALE_EMPTY_PRODUCTS: "La venta debe tener al menos un producto",
    SALE_INVALID_PAYMENT_METHOD: "Método de pago no soportado",
    SALE_INVALID_AMOUNT: "El monto del pago es inválido",
    SALE_PAYMENT_EXCEEDS_TOTAL: "El pago excede el total de la venta",
    SALE_STATUS_CANCELLED: "No se puede procesar una venta cancelada",
    SALE_CANNOT_CANCEL_COMPLETED: "No se puede cancelar una venta completada",
    SALE_INVALID_DETAIL: "Detalle de venta inválido",
    SALE_TICKET_ALREADY_GENERATED: "El ticket ya fue generado",
    SALE_DUPLICATE_DETAIL: "Producto duplicado en la venta",
    SALE_INVALID_PAYMENT_STATE: "Estado de pago inválido",
    SALE_INSUFFICIENT_PAYMENT: "Pago insuficiente",

    // Image Upload
    IMAGE_SERVICE_UNAVAILABLE: "Servicio de imágenes no disponible",
    IMAGE_NOT_UPLOADED: "La imagen no pudo ser cargada",
    IMAGE_NOT_DELETED: "La imagen no pudo ser eliminada",
};